#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to respect below requirements
# (this script will be run on the server itself)
# Install nginx on your web-01
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl
#    it must return a page that contains the string Hello World!
sudo apt-get update
sudo apt-get install -y nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
