#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to respect below requirements
# Configure Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page
sudo apt-get update
sudo apt-get install -y nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo ufw allow 'Nginx HTTP'
echo -e "Ceci n'est pas une page\n" > /usr/share/nginx/html/404.html
sudo sed -i "s/server_name _;/server_name _;\n\tlocation \/redirect_me {\n\t\t return 301 http:\/\/google.com;\n\t}\n\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default
sudo service nginx start
