#!/usr/bin/env bash
# Bash script that configures the container to run nginx as nginx user on port 8080
chmod 777 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx start
